AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Convert a birthday into age information.

Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: Convert a birthday into age information.
      CodeUri: dist/
      Handler: handler
      Runtime: go1.x
      Tracing: Active

Metadata:
  AWS::ServerlessRepo::Application:
    Name: birthday-to-age
    Description: Convert a birthday into age information.
    Author: sbstjn
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE.md
    ReadmeUrl: README.md
    Labels:
      - sbstjn
      - superluminar
      - serverless
      - serverlessdays
      - workshop
      - suchfeatures
      - nocode
    HomePageUrl: https://github.com/sbstjn/lambda-birthday-to-age
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/sbstjn/lambda-birthday-to-age

Outputs:
  HelloWorldFunction:
    Description: Function ARN
    Value: !GetAtt Function.Arn
