AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Convert a birthday into age information.

Globals:
  Function:
    Timeout: 5

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Description: Convert a birthday into age information.
      CodeUri: dist/
      Handler: handler
      Runtime: go1.x
      Tracing: Active

Outputs:
  HelloWorldFunction:
    Description: Function ARN
    Value: !GetAtt Function.Arn
